adminTab=//span[text()='Admin']
addButton=//button[normalize-space()='Add']
userRoleDropdown=//label[text()='User Role']//ancestor::div[@class='oxd-input-group oxd-input-field-bottom-space']//div[@class='oxd-select-wrapper']
userRoleESSOption=//span[text()='ESS']
userRoleAdminOption=//span[text()='Admin']
statusDropdown=//label[text()='Status']//ancestor::div[@class='oxd-input-group oxd-input-field-bottom-space']//div[@class='oxd-select-wrapper']
enabledOption=//span[text()='Enabled']
disabledOption=//span[text()='Disabled']
employeeNameInput=//input[@placeholder='Type for hints...']
selectEmployeeFromDropdown=//span[text()='Ravi M B']
usernameField=//label[text()='Username']//ancestor::div[@class='oxd-input-group oxd-input-field-bottom-space']//input
passwordField=//label[text()='Password']//ancestor::div[@class='oxd-input-group oxd-input-field-bottom-space']//input
confirmPasswordField=//label[text()='Confirm Password']//ancestor::div[@class='oxd-input-group oxd-input-field-bottom-space']//input
cancelButton=//button[normalize-space()='Cancel']
saveButton=//button[normalize-space()='Save']
successToasterMessageForSavedUser=//p[text()='Successfully Saved']