usernameField = //input[@name='username']
passwordField = //input[@name='password']
loginButton = //button[@type='submit']
forgotPasswordLink =//p[normalize-space()='Forgot your password?']
profileIcon = //img[@alt='profile picture']
logoutButton = //a[text()='Logout']