extent.reporter.spark.start=true
extent.reporter.spark.config=src/test/resources/extent-config.xml
basefolder.name=ExtendReport
basefolder.datetimepattern=d-MM-YY HH-mm-ss
extent.reporter.spark.out=Spark.html
extent.reporter.spark.base64imagesrc=true
screenshot.dir=test-output/
screenshot.rel.path=../
extent.reporter.spark.vieworder=dashboard,test,exception,log
systeminfo.os=windows
systeminfo.user=Laxmi Maurya
systeminfo.environment=Staging
